### ISSUE TITLE
Offsets in file format descriptions should be displayed in hexadecimal notation

### ISSUE THREAD

**Issue by Argent77** [Gibberlings3/iesdp#118]
The following file format descriptions currently display data offsets in decimal instead of hexadecimal notation:
- EFF V1
- EFF V2
- ITM V1
- SPL V1

**Comment by lynxlynxlynx** [comment]
Crap, looks like the plugins don't work after the migration to github actions. It's the same for hex numbering of opcodes.

**Comment by lynxlynxlynx** [comment]
Finally nailed this down. :)

**Comment by 4Luke4** [comment]
> Finally nailed this down. :)

Nice!

What about removing unnecessary `0`s (zeros)?
So for instance `0x60` instead of `0x0060`...?

**Comment by lynxlynxlynx** [comment]
It could be done when post-processing, but then all files would have to be changed to match, the widths would vary and in general I don't see the tiny readability improvement as worth it.
