### ISSUE TITLE
Opcode names are not properly generated

### ISSUE THREAD

**Issue by Argent77** [Gibberlings3/iesdp#141]
Opcode names are currently displayed as __`#0 (0x0) op000.html`__ or __`#1 (0x1) op001-bgee.html`__, instead of their actual names.

All game variants are affected.

**Comment by lynxlynxlynx** [comment]
Thanks, that's odd. I suspect jekyll got updated on the backend and we have a naming collision. We use a "name" var for the opcode name, which is generic enough to give me pause.

**Comment by lynxlynxlynx** [comment]
Yeah, it was exactly that, see `page.name` in https://jekyllrb.com/docs/variables/
Time for a rename.
