### ISSUE TITLE
PROFSMAX.2DA for BGEE is wrong

### ISSUE THREAD

**Issue by lucasmr** [Gibberlings3/iesdp#158]
[PROFSMAX](https://gibberlings3.github.io/iesdp/files/2da/2da_bgee/profsmax.htm)

This is either wrong or being overridden by another file. The description is also the same as pre-EE and doesn't explain the additional columns.

**Comment by lynxlynxlynx** [comment]
What do you think is wrong?
I have no idea if the extra columns are used for anything.

**Comment by lucasmr** [comment]
Compare with the original [PROFSMAX](https://gibberlings3.github.io/iesdp/files/2da/2da_tots/profsmax.htm) from TotSC, the max proficiencies make sense.

**Comment by lynxlynxlynx** [comment]
Doesn't matter, this is the file that's shipped. Perhaps the table got superceeded or hardcoded again.

**Comment by lucasmr** [comment]
Alright, thanks.
