### ISSUE TITLE
[Documentation] Could https://github.com/gibberlings3/iesdp//blob/master/file_formats/ie_formats/itm_v1.htm provide a hint at the end or somewhere else, how to modify items?

### ISSUE THREAD

**Issue by rubyFeedback** [Gibberlings3/iesdp#164]
I am trying to add new items to a mod but I am not quite sure yet how to modify the items data or add new items.

**Comment by lynxlynxlynx** [comment]
That's out of scope for IESDP. Look at existing tutorials and guides like https://www.gibberlings3.net/forums/topic/2581-tutorial-item-patching/.
