### ISSUE TITLE
Duplicate opcode description entries for BGEE and PSTEE

### ISSUE THREAD

**Issue by Argent77** [Gibberlings3/iesdp#171]
Several opcode descriptions are listed twice:
- [op219 (BGEE)](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op219)
- [op219 (PSTEE)](https://gibberlings3.github.io/iesdp/opcodes/pstee.htm#op219)
- [op238 (BGEE)](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op238)
- [op238 (PSTEE)](https://gibberlings3.github.io/iesdp/opcodes/pstee.htm#op238)

The opcode descriptions seem to differ slightly.

**Comment by lynxlynxlynx** [comment]
Yeah, thanks, the keys are not set exclusively, will fix.
