### ISSUE TITLE
BG1EE - Action 182 MakeUnselectable() does not stop processing creature scripts

### ISSUE THREAD

**Issue by agb1** [Gibberlings3/iesdp#27]
On BG2:EE, [this action description](https://gibberlings3.github.io/iesdp/scripting/actions/bg1actions.htm#182) is correct:

182 MakeUnselectable(I:Time*)
This action changes the active creature's selection circle to purple - making it unselectable. **Creatures made unselectable stop processing scripts.**

For BG1:EE, the bold part above is not correct.  Creature scripts are still processed after this action.

For BG2:EE, engine.lua contains an option named **engine_mode** that defaults to 1 (BG2:EE mode).  Setting engine_mode to 0 (BG1:EE mode) causes the action description to be true (i.e., if engine_mode = 0 = BG1:EE mode, scripts are processed even for creatures that were made unselectable by action 182).

The new EE [opcode 365](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op365), unlike this script action, can be used to make creatures stop processing scripts while unselectable even for engine_mode = 1.

I suggest revising the action description as follows:

182 MakeUnselectable(I:Time*)
This action changes the active creature's selection circle to purple and makes it unselectable. If engine_mode = 0 (default setting for BG1:EE) in engine.lua, the creature continues processing scripts while unselectable. If engine_mode = 1 (default setting for BG2:EE), the creature stops processing scripts while unselectable. For both BG1:EE and BG2:EE, you can use [opcode 365](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op365) to make creatures unselectable without disabling their script processing.

Original analysis by K4thos:  http://gibberlings3.net/forums/index.php?showtopic=27741&p=248243

**Comment by K4thos** [comment]
agb1, I think by "and also disable their script processing" you meant something like "without disabling their script processing"

**Comment by lynxlynxlynx** [comment]
Interesting, I didn't know they bothered keeping the engines different. Is there more documentation on engine_mode somewhere? It potentially changes other actions and/or opcodes.

**Comment by agb1** [comment]
Oops.  You're right, K4thos.  I had that backwards.  Here's a revision is corrected and flows better (putting the two BG2:EE related sentences together at the end and putting BG1:EE first).

182 MakeUnselectable(I:Time*)
This action changes the active creature's selection circle to purple and makes it unselectable. If engine_mode = 0 (default setting for BG1:EE), the creature continues processing scripts while unselectable. If engine_mode = 1 (default setting for BG2:EE) in engine.lua, the creature stops processing scripts while unselectable. For BG2:EE, you can use opcode 365 to make creatures unselectable **without disabling their script processing**.

K4thos also suggested a separate improvement to the opcode 365 description:  The UnselectableVariableGT(0) trigger will be true in the scripts of creatures affected by this opcode.

I assume this trigger always applies to the creature running the script...

**Comment by agb1** [comment]
Maybe change "For BG2:EE" in the last sentence to "For both BG:EE and BG2:EE" ... since the opcode works for both (again, I assume).

**Comment by lynxlynxlynx** [comment]
Please just edit your intro post, so it will be easier to review for everyone.

**Comment by agb1** [comment]
I revised my first post.

**Comment by lynxlynxlynx** [comment]
Thanks for the notes, it's now finally in.
