### ISSUE TITLE
Migrating IESDP to Lightweight markup language

### ISSUE THREAD

**Issue by winterheart** [Gibberlings3/iesdp#29]
Hello.
It seems IEDSP currently have huge maintenance because it written in pure HTML + JavaScript. Meanwhile it stops to effectively add and review new portions of information (mainly from EE editions).

Can we migrate whole IEDSP to some markup language, intended for documentation? I can suggest [Markdown](https://en.wikipedia.org/wiki/Markdown) or (preferably) [reStructuredText](https://en.wikipedia.org/wiki/ReStructuredText). Both have their pros and cons, but undoubtedly, both are better solution than current pure HTML.

**Comment by lynxlynxlynx** [comment]
First, there is no indication the format is stopping contributions or increasing the maintenance burden — it's a documentation project after all, so there is almost only content maintenance needed. When I partly jekyllized it, that became even more true.

Jekyll can compile into HTML easily, so feel free to try out a different renderer (I think only markdown is there by default). If markdown can live alongside existing HTML without changes, then it would at least not be a waste of huge effort. If not, who is going to convert all the content into the new format? All that time could be better spent fixing existing issues, especially the content backlog.

Make your case.

**Comment by winterheart** [comment]
I've prepared demo: http://iesdp-rst.readthedocs.io/en/latest/ (source git here: https://github.com/winterheart/iesdp-rst)

My main intention was not only ease maintenance, but provide IESDP to different formats. Plus, ReStructuredText + Sphinx give a lot nice little features:

* Automatically generated TOC and Index: http://iesdp-rst.readthedocs.io/en/latest/genindex.html
* Support for ZIPped HTML, ePub and PDF out of box (OK, that rather ReadTheDocs feature, but standalone solution also available): http://readthedocs.org/projects/iesdp-rst/downloads/htmlzip/latest/ http://readthedocs.org/projects/iesdp-rst/downloads/pdf/latest/ 
* Reporting for coverage, integrity and dead or broken links (`make linkcheck`)
* Built-in support for TODOs: http://iesdp-rst.readthedocs.io/en/latest/todos.html
* Fully customizable HTML-theme (current is sphinx_bootstrap_theme)
* And many many others.

And yes, there huge working for manual migration. I tried to use pandoc for this, but currently IEDSP highly unstructured, so migration can be done only manually. I can do this but this process would be slow - about 3-4 months since each page has own formatting and style. There should also some time for generating conventions and code style.

**Comment by lynxlynxlynx** [comment]
But who needs any of that? I've been in the community for around 10 years and nobody complained even about the spartan looks, let alone more complicated stuff. The little bit of structure I added to the opcodes also received some negative feedback, so it's pretty clear the community is conservative about looks.

So really, what is truly lacking in IESDP **for you** that you're considering spending several months just editing html? The only user facing thing on your list are the export options, but that can also be achieved in other ways, besides the fact that there is probably a miniscule amount of devices that can't display html.
