### ISSUE TITLE
Proposal: change design of tables

### ISSUE THREAD

**Issue by hjred** [Gibberlings3/iesdp#32]
Browsing through the iesdp, there was always one thing that looked kind of misplaced and that is the design of the tables on the site.
I changed only some values for the tables in css to look (in my opinion) a little bit more clean and unobtrusive.
Here is a before and after comparison:

![old_design](https://user-images.githubusercontent.com/11563941/29208340-f240b030-7e89-11e7-9c11-db40bbc6b001.png)

![new_design](https://user-images.githubusercontent.com/11563941/29208346-f93da2a8-7e89-11e7-9836-a7f976beeb37.png)

Checked with IE, Edge and Firefox.

If your happy with the change, i can create a pull request.

**Comment by lynxlynxlynx** [comment]
Much better indeed, especially the padding. I guess the column widths are hardcoded at the moment? Ideally we'd also increase the width of the size column, so there'd be now wrap.

**Comment by hjred** [comment]
Yeah, the column widths are hardcoded in each and every table. I tried to change as little as possible to make the general appearance a little better.

Will add the general layout changes as a seperate commit to the pull request. This should not interfere with all other changes.

**Comment by hjred** [comment]
I think i found a way with pure css to disable wrapping of certain elements, will do some testing ...

**Comment by lynxlynxlynx** [comment]
yeah, css has everything for tables, I just don't know how browsers treat it, what has precedence.

**Comment by hjred** [comment]
The minimal width of the tables are now automatically as wide as the table header cell text, they can grow bigger, but are not allowed to wrap the text. This prevents the wrapping of the data type cells as well.
