### ISSUE TITLE
BG(2)EE actions reference bg2 identifiers

### ISSUE THREAD

**Issue by hjred** [Gibberlings3/iesdp#38]
All actions in BG(2)EE with references to ids files reference the BG2 versions even if an appropriate ids file for BG(2)EE exists. Is this intentional or an oversight?

**Comment by lynxlynxlynx** [comment]
definitely a bug.

**Comment by hjred** [comment]
Then i would update them and see if this is the case for other games as well.

**Comment by hjred** [comment]
Only the BG(2)EE version has errors, the others are correct
