### ISSUE TITLE
Use consistent line breaks in files

### ISSUE THREAD

**Issue by Argent77** [Gibberlings3/iesdp#60]
Currently, files are using either Unix-style or Windows-style line breaks. A great number of them even use both at the same time which confuses text editors and will therefore add unnecessary noise to diffs. 

Change all of them to Unix-style for consistency (and smaller file size).

**Comment by lynxlynxlynx** [comment]
Agreed, it's annoying since it drowns the diffs. A trivial fix though, on it.
