### ISSUE TITLE
.ITM file format, BG:EE support of BMP in item description

### ISSUE THREAD

**Issue by metamaker** [Gibberlings3/iesdp#65]
I see that due to recent change https://github.com/Gibberlings3/iesdp/commit/4a7c930d3bf6beb74c89dfbd99e341c2fb4d2548#diff-8b120e9d83d6c8fe0b7792aeff65cc08 you marked that if at offset `0x0058 Description icon (BAM)` I specify resref of BMP, BG:EE should catch it (`Note: BGEE also supports BMP`). However, my friend tried to do this and it doesn't work (he dropped BMP file with same name into /override instead of BAM file). BAM files, on other hand, work perfectly. Can you confirm somehow that it really works in BG:EE? Thanks in advance!

**Comment by lynxlynxlynx** [comment]
Was it a valid BMP file?
@Argent77

**Comment by metamaker** [comment]
> Was it a valid BMP file?
Yes. Same width/height and color depth.

**Comment by Argent77** [comment]
I took that info from current Near Infinity implementation. This [particular change](https://github.com/Argent77/NearInfinity/commit/6d990b110f08567e7f6f805fc6ab1adeb089f7d1) was implemented around November 2013.

I have just tested it in BG1EE v2.3.67.3 where it didn't work. Testing in v1.3.2053 worked though. Looks like Beamdog removed BMP support in v2.x. Will update field description.

**Comment by lynxlynxlynx** [comment]
Thanks to both!
