### ISSUE TITLE
How to present PSTEE-specific information?

### ISSUE THREAD

**Issue by Argent77** [Gibberlings3/iesdp#67]
PSTEE is unusual compared to the other Enhanced Editions games, even though it is based on roughly the same game engine revision. The biggest difference is currently the number of available script actions and triggers, as well as effect opcodes.

I can think of two viable options how to present information specific to this game:

1. Use separate pages for PSTEE.<br />Advantage: Information is presented in a clear and precise way.<br />Disadvantage: A great number of duplicate information that has to be kept in sync with the other EE games.

2. Add PSTEE-specific information to the BG(2)EE pages.<br />Advantage: No danger of pages getting out of sync (less work for maintainers). Since EE games are still getting patched it is possible that PSTEE-specific features are ported to the other games as well.<br />Disadvantage: Pages may tend to get overloaded with information. It's more difficult to pick out information for specific games.

Alternatively, information could be added to the PST pages. But since PSTEE is much closer to BG(2)EE than to PST, it would get even more confusing.

@lynxlynxlynx @btigi What's your take on this?

**Comment by lynxlynxlynx** [comment]
Do I remember correctly that BD is extra slow with patching? IOW would it be silly to wait for them to unify the engines of all three games?

**Comment by Argent77** [comment]
I doubt they will do that. BD has mentioned on several occasions that they don't intent to port everything from PSTEE over to the other games. The PST-specific stuff will probably remain PSTEE-only. But I agree that it wouldn't hurt to wait for the next batch of game patches first.

**Comment by btigi** [comment]
I'm definitely in favour of separate pages, one page per engine (as a side note I feel the same way on the opcodes).

**Comment by lynxlynxlynx** [comment]
The opcodes are still one page per engine and that part is the easiest to tackle, as it will be much harder to get the versions out of sync. Action data could be shared in a similar manner, but that would require some infrastructural work first. 2das+ids are boring and static enough to just be copied for now.

**Comment by Argent77** [comment]
Following up on this issue, I have compiled a list of opcodes specifically for the PSTEE engine variant. Opcode 0 to 367 are identical with the other EE engine games. PSTEE provides additional opcodes 368 to 383, where most of them are functionally identical to selected PST opcodes.

I'd prefer to add them to the BGEE opcode page with a note that these opcodes are only available for PSTEE. Creating a separate PSTEE page would just further complicate matters, since updates for BGEE would have to be synced with the PSTEE variant. Thoughts?

**Comment by lynxlynxlynx** [comment]
That's a false dilemma, since the opcodes have been deduplicated. So if we wanted a separate opcode page just for pstee, that would be simple without requiring extra maintenance on the first 368 opcodes.

To get those listed for pstee, you'd just append "pstee: 1" to all the opcode files that have "bgee: 1", eg. https://github.com/Gibberlings3/iesdp/blob/master/_opcodes/op001-bgee.html
The listing page is a simple loop over this "collection".

**Comment by Argent77** [comment]
Solved.
