### ISSUE TITLE
Opcode #321 - Timing mode

### ISSUE THREAD

**Issue by 4Luke4** [Gibberlings3/iesdp#75]
IMHO, the following part _"If used with a timing mode other than Duration (0) the effect behaves as per effect 206."_ is not very clear.
What about putting something like this?

_"It always needs to be the first effect for stacking prevention.
Timing Mode should be either Instant/Limited(0) with 0 duration, or Instant/Permanent(1)."_

**Comment by lynxlynxlynx** [comment]
Sure, please submit a pull request.

**Comment by 4Luke4** [comment]
> Sure, please submit a pull request.

Done.
To be honest, I took the opportunity to tweak/fix some other opcodes,  so please check and review my pull request...
