### ISSUE TITLE
Labels for actions

### ISSUE THREAD

**Issue by burner1024** [Gibberlings3/iesdp#85]
I think that notes like "This action has not been seen to produce any results" or "Not tested" would be more visible and better represented by labels similar to github issue labels.
![Captura de pantalla de 2020-02-23 14-59-09](https://user-images.githubusercontent.com/1279852/75106260-16033180-564d-11ea-89ba-19ad96aad73a.png).
How about that?

**Comment by lynxlynxlynx** [comment]
Same for any crashers.

For some of them they may apply to actions that have variants in other engines, so I'm not sure it'd look good after the title. Some are long too. Play with it, I'd put them before the sisters block.

I propose you use another yaml var for freeform warning text, then style it yellow in the layout.

**Comment by burner1024** [comment]
Does action color itself carry meaning? Why 98+ are blue, are they also "not seen to produce any result"?

![Captura de pantalla de 2020-02-23 16-18-22](https://user-images.githubusercontent.com/1279852/75109677-22d95280-5658-11ea-873e-d05c3af003d4.png)

**Comment by lynxlynxlynx** [comment]
Judging from the class of "unknown", I suspect igi had it as a marker of unverified information.

**Comment by burner1024** [comment]
OK, so "not tested", then.

**Comment by burner1024** [comment]
Here's a sample
![Captura de pantalla de 2020-02-23 18-38-28](https://user-images.githubusercontent.com/1279852/75111393-bff1b680-566b-11ea-9ca2-c35504e23fa4.png)

**Comment by lynxlynxlynx** [comment]
Brings up an interesting point — don't forget to add it to the other 97 variant, which requires a separate file.

**Comment by burner1024** [comment]
I'll check when I get to variants, but I think everything should work as is, since they are essentially independent.
